// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZpVLcvVl1F97QXzpYCoC8Yw3ja-b-akc',
    appId: '1:189463239788:web:a6a6dfd3dc6c7db7ff4c49',
    messagingSenderId: '189463239788',
    projectId: 'landk-d29f0',
    authDomain: 'landk-d29f0.firebaseapp.com',
    storageBucket: 'landk-d29f0.appspot.com',
    measurementId: 'G-EZCGWNTN58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnO0YYdt_qFW_WwuHFlMCiJM-t31PUu7M',
    appId: '1:189463239788:android:53338811f204cfa4ff4c49',
    messagingSenderId: '189463239788',
    projectId: 'landk-d29f0',
    storageBucket: 'landk-d29f0.appspot.com',
  );
}
