// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1l4nDBsSts-eUGjuRLTmU1a3U6DqfTM',
    appId: '1:188186765987:web:4eaaa84641d3604b462d16',
    messagingSenderId: '188186765987',
    projectId: 'fir-multi-vendor-fa07d',
    authDomain: 'fir-multi-vendor-fa07d.firebaseapp.com',
    databaseURL: 'https://fir-multi-vendor-fa07d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-multi-vendor-fa07d.appspot.com',
    measurementId: 'G-JHBKNTPJKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK5gSlMl2YTeyixpDFIKoN_8l3Ez80mwQ',
    appId: '1:188186765987:android:e4022ece4ce67d00462d16',
    messagingSenderId: '188186765987',
    projectId: 'fir-multi-vendor-fa07d',
    databaseURL: 'https://fir-multi-vendor-fa07d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-multi-vendor-fa07d.appspot.com',
  );
}
